name: CI
on:
  push:
    branches-ignore:
      - master
    paths:
      - "*.json"
      - "packages/**"
      - .github/workflows/ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - datemate
          - cidrmate
          - urlmate
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup 🔧
        uses: actions/setup-node@v4
      - name: Clean Install 🧹
        run: |
          npm i --workspace @somethingmate/${{matrix.package}}
          npm ci --workspace @somethingmate/${{matrix.package}}
      - name: Build 🚧
        run: npm run build --workspace @somethingmate/${{matrix.package}}

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - datemate
          - cidrmate
          - urlmate
          - shared
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup 🔧
        uses: actions/setup-node@v4
      - name: Clean Install 🧹
        run: |
          npm i --workspace @somethingmate/${{matrix.package}}
          npm ci --workspace @somethingmate/${{matrix.package}}
      - name: Test 🚦
        run: npm test --workspace @somethingmate/${{matrix.package}}
